# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "2"

volumes:
  orderer0.org1.example.com:
  orderer0.org2.example.com:
  orderer0.org3.example.com:
  orderer0.org4.example.com:

networks:
  test:

services:
  orderer0.org1.example.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer0.org1.example.com
    environment:
      - ORDERER_GENERAL_LOCALMSPID=Org1MSP
    networks:
      - test
    volumes:
      - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../organizations/peerOrganizations/org1.example.com/orderers/orderer0.org1.example.com/msp:/var/hyperledger/orderer/msp
      - ../organizations/peerOrganizations/org1.example.com/orderers/orderer0.org1.example.com/tls/:/var/hyperledger/orderer/tls
      - orderer0.org1.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  orderer0.org2.example.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer0.org2.example.com
    environment:
      - ORDERER_GENERAL_LOCALMSPID=Org2MSP
    networks:
      - test
    volumes:
      - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../organizations/peerOrganizations/org2.example.com/orderers/orderer0.org2.example.com/msp:/var/hyperledger/orderer/msp
      - ../organizations/peerOrganizations/org2.example.com/orderers/orderer0.org2.example.com/tls/:/var/hyperledger/orderer/tls
      - orderer0.org2.example.com:/var/hyperledger/production/orderer
    ports:
      - 9050:7050

  orderer0.org3.example.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer0.org3.example.com
    environment:
      - ORDERER_GENERAL_LOCALMSPID=Org3MSP
    networks:
      - test
    volumes:
      - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../organizations/peerOrganizations/org3.example.com/orderers/orderer0.org3.example.com/msp:/var/hyperledger/orderer/msp
      - ../organizations/peerOrganizations/org3.example.com/orderers/orderer0.org3.example.com/tls/:/var/hyperledger/orderer/tls
      - orderer0.org3.example.com:/var/hyperledger/production/orderer
    ports:
      - 11050:7050

  orderer0.org4.example.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer0.org4.example.com
    environment:
      - ORDERER_GENERAL_LOCALMSPID=Org4MSP
    networks:
      - test
    volumes:
      - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../organizations/peerOrganizations/org4.example.com/orderers/orderer0.org4.example.com/msp:/var/hyperledger/orderer/msp
      - ../organizations/peerOrganizations/org4.example.com/orderers/orderer0.org4.example.com/tls/:/var/hyperledger/orderer/tls
      - orderer0.org4.example.com:/var/hyperledger/production/orderer
    ports:
      - 13050:7050
